//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakFaser
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeointegrasjonFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SakFaser.ApplicationFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SakFaser.FinderFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SakFaser.ValidationFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SakFaser.SystemFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SakFaser.ImplementationFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SakFaser.OperationalFault))]
    public partial class GeointegrasjonFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string feilKodeField;
        
        private string feilBeskrivelseField;
        
        private SakFaser.StringListe feilDetaljerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string feilKode
        {
            get
            {
                return this.feilKodeField;
            }
            set
            {
                this.feilKodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string feilBeskrivelse
        {
            get
            {
                return this.feilBeskrivelseField;
            }
            set
            {
                this.feilBeskrivelseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SakFaser.StringListe feilDetaljer
        {
            get
            {
                return this.feilDetaljerField;
            }
            set
            {
                this.feilDetaljerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SakFaser.FinderFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SakFaser.ValidationFault))]
    public partial class ApplicationFault : SakFaser.GeointegrasjonFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinderFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class FinderFault : SakFaser.ApplicationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class ValidationFault : SakFaser.ApplicationFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SakFaser.ImplementationFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SakFaser.OperationalFault))]
    public partial class SystemFault : SakFaser.GeointegrasjonFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImplementationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class ImplementationFault : SakFaser.SystemFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationalFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class OperationalFault : SakFaser.SystemFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StringListe", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31", ItemName="liste")]
    public class StringListe : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31", ConfigurationName="SakFaser.SaksfaserPort")]
    public interface SaksfaserPort
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SakFaser.SystemFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="SystemFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.FaultContractAttribute(typeof(SakFaser.ImplementationFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="ImplementationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.FaultContractAttribute(typeof(SakFaser.OperationalFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="OperationalFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.FaultContractAttribute(typeof(SakFaser.ApplicationFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="ApplicationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.FaultContractAttribute(typeof(SakFaser.FinderFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="FinderFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.FaultContractAttribute(typeof(SakFaser.ValidationFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="ValidationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saksnoekkel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SakFaser.HentFaserForSakResponse HentFaserForSak(SakFaser.HentFaserForSak request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Arkiv/Felles/xml.schema/2012.01.31")]
    public partial class Saksnummer : Saksnoekkel
    {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string saksaar
        {
            get
            {
                return this.saksaarField;
            }
            set
            {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string sakssekvensnummer
        {
            get
            {
                return this.sakssekvensnummerField;
            }
            set
            {
                this.sakssekvensnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Saksnummer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Arkiv/Felles/xml.schema/2012.01.31")]
    public partial class Saksnoekkel
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31")]
    public partial class Milepel
    {
        
        private string milepelNavnField;
        
        private string milepelBeskrivelseField;
        
        private System.DateTime milepelDatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string milepelNavn
        {
            get
            {
                return this.milepelNavnField;
            }
            set
            {
                this.milepelNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string milepelBeskrivelse
        {
            get
            {
                return this.milepelBeskrivelseField;
            }
            set
            {
                this.milepelBeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime milepelDato
        {
            get
            {
                return this.milepelDatoField;
            }
            set
            {
                this.milepelDatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaseStatus))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KoordinatsystemKode))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Kodeliste/xml.schema/2012.01.31")]
    public partial class Kode
    {
        
        private string kodeverdiField;
        
        private string kodebeskrivelseField;
        
        private bool erGyldigField;
        
        private bool erGyldigFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string kodeverdi
        {
            get
            {
                return this.kodeverdiField;
            }
            set
            {
                this.kodeverdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kodebeskrivelse
        {
            get
            {
                return this.kodebeskrivelseField;
            }
            set
            {
                this.kodebeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool erGyldig
        {
            get
            {
                return this.erGyldigField;
            }
            set
            {
                this.erGyldigField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool erGyldigSpecified
        {
            get
            {
                return this.erGyldigFieldSpecified;
            }
            set
            {
                this.erGyldigFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31")]
    public partial class FaseType : Kode
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31")]
    public partial class FaseStatus : Kode
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    public partial class KoordinatsystemKode : Kode
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31")]
    public partial class Fase
    {
        
        private string faseNavnField;
        
        private string faseBeskrivelseField;
        
        private FaseType typeField;
        
        private FaseStatus statusField;
        
        private Milepel startMilepelField;
        
        private Milepel sluttMilepelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string faseNavn
        {
            get
            {
                return this.faseNavnField;
            }
            set
            {
                this.faseNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faseBeskrivelse
        {
            get
            {
                return this.faseBeskrivelseField;
            }
            set
            {
                this.faseBeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FaseType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public FaseStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Milepel startMilepel
        {
            get
            {
                return this.startMilepelField;
            }
            set
            {
                this.startMilepelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Milepel sluttMilepel
        {
            get
            {
                return this.sluttMilepelField;
            }
            set
            {
                this.sluttMilepelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HentFaserForSak", WrapperNamespace="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31", IsWrapped=true)]
    public partial class HentFaserForSak
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31", Order=0)]
        public SakFaser.Saksnummer saksnummer;
        
        public HentFaserForSak()
        {
        }
        
        public HentFaserForSak(SakFaser.Saksnummer saksnummer)
        {
            this.saksnummer = saksnummer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HentFaserForSakResponse", WrapperNamespace="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31", IsWrapped=true)]
    public partial class HentFaserForSakResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("liste", Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31", IsNullable=false)]
        public SakFaser.Fase[] @return;
        
        public HentFaserForSakResponse()
        {
        }
        
        public HentFaserForSakResponse(SakFaser.Fase[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SaksfaserPortChannel : SakFaser.SaksfaserPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaksfaserPortClient : System.ServiceModel.ClientBase<SakFaser.SaksfaserPort>, SakFaser.SaksfaserPort
    {
        
        public SaksfaserPortClient()
        {
        }
        
        public SaksfaserPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SaksfaserPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SaksfaserPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SaksfaserPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SakFaser.HentFaserForSakResponse SakFaser.SaksfaserPort.HentFaserForSak(SakFaser.HentFaserForSak request)
        {
            return base.Channel.HentFaserForSak(request);
        }
        
        public SakFaser.Fase[] HentFaserForSak(SakFaser.Saksnummer saksnummer)
        {
            SakFaser.HentFaserForSak inValue = new SakFaser.HentFaserForSak();
            inValue.saksnummer = saksnummer;
            SakFaser.HentFaserForSakResponse retVal = ((SakFaser.SaksfaserPort)(this)).HentFaserForSak(inValue);
            return retVal.@return;
        }
    }
}
